#!/usr/bin/env python3
"""scripts/zip-project.py

Create a clean zip of the project for download, excluding bulky/irrelevant
files (node_modules, .git, downloaded CSV data, generated tile files,
log files of failed runs).

Output: /home/z/my-project/download/galaxy-flythrough.zip

The zip is structured so that the project root is at the top level of the
archive — i.e. unzipping produces:
    galaxy-flythrough/
      AGENTS.md
      plan.md
      findings-pitfalls-skills.md
      archive/
      experiments/
      scripts/
      src/
      download/
"""

import datetime
import os
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT_ZIP = ROOT / 'download' / 'galaxy-flythrough.zip'
TOP_DIR_NAME = 'galaxy-flythrough'  # top-level directory inside the zip

# --- What to include / exclude ---
INCLUDE_DIRS = [
    'archive',
    'experiments',
    'scripts',
    'src',
]

INCLUDE_FILES = [
    'AGENTS.md',
    'plan.md',
    'findings-pitfalls-skills.md',
    'worklog.md',
    # Include the visualization PNG so the user can see the galaxy
    # without having to run any code first.
    'download/galaxy-viz.png',
]

# Glob-style patterns to exclude (matched against full path inside the project)
EXCLUDE_PATTERNS = [
    'node_modules',
    '.git',
    '__pycache__',
    '*.pyc',
    '.DS_Store',
    # Skills directory is huge and not part of the project
    'skills',
    # Upload/research are not part of the project
    'upload',
    'research',
    # Generated data (kept small)
    'src/data/tiles',         # tile files are regenerated by tile-encoder.js
    'src/data/gaia-subset.csv',  # downloaded from Gaia archive
    # Large logs
    'experiments/logs/galaxy-sample.json',  # 5 MB; regenerated by visualize-data
    # The zip output itself (we don't want to zip ourselves)
    'galaxy-flythrough.zip',
    # Old plan in download/ (kept in archive/)
    'galaxy-flythrough-dev-plan.md',
]


def matches_exclusion(path: Path, rel: str) -> bool:
    """Check if a path matches any exclusion pattern."""
    parts = path.parts
    for pat in EXCLUDE_PATTERNS:
        # Treat pattern as a simple path fragment match
        if '/' in pat:
            # Path-like pattern: check substring
            if pat in rel.replace(os.sep, '/'):
                return True
        else:
            # Single-token pattern: check if any path part matches (with glob)
            if pat in parts:
                return True
            # Filename glob (e.g. *.pyc)
            if pat.startswith('*'):
                ext = pat[1:]
                if path.name.endswith(ext):
                    return True
    return False


def add_dir_to_zip(zf: zipfile.ZipFile, dir_path: Path, top_dir: str):
    """Recursively add a directory to the zip under top_dir/."""
    for root, dirs, files in os.walk(dir_path):
        # Filter out excluded dirs in-place
        dirs[:] = [d for d in dirs if not matches_exclusion(Path(root) / d, str((Path(root) / d).relative_to(ROOT)))]
        for fname in files:
            full = Path(root) / fname
            rel = str(full.relative_to(ROOT))
            if matches_exclusion(full, rel):
                continue
            arcname = f'{top_dir}/{rel.replace(os.sep, "/")}'
            zf.write(str(full), arcname=arcname)


def add_file_to_zip(zf: zipfile.ZipFile, file_path: Path, top_dir: str):
    """Add a single file to the zip under top_dir/, preserving subdirs."""
    if not file_path.exists():
        print(f'  (skip, not found: {file_path})')
        return
    # Preserve relative path under ROOT (so download/galaxy-viz.png stays at
    # galaxy-flythrough/download/galaxy-viz.png)
    rel = file_path.relative_to(ROOT)
    arcname = f'{top_dir}/{rel.as_posix()}'
    zf.write(str(file_path), arcname=arcname)


def main():
    print('=== Creating project zip ===')
    print(f'  root:    {ROOT}')
    print(f'  output:  {OUT_ZIP}')
    print(f'  top dir: {TOP_DIR_NAME}/')
    print()

    # Make sure output dir exists
    OUT_ZIP.parent.mkdir(parents=True, exist_ok=True)

    # Remove any previous zip
    if OUT_ZIP.exists():
        OUT_ZIP.unlink()

    file_count = 0
    byte_count = 0

    with zipfile.ZipFile(OUT_ZIP, 'w', zipfile.ZIP_DEFLATED, compresslevel=6) as zf:
        # Add top-level files
        print('Adding top-level files:')
        for fname in INCLUDE_FILES:
            fpath = ROOT / fname
            print(f'  {fname} ...')
            add_file_to_zip(zf, fpath, TOP_DIR_NAME)
            if fpath.exists():
                file_count += 1
                byte_count += fpath.stat().st_size

        # Add directories
        print()
        print('Adding directories:')
        for dname in INCLUDE_DIRS:
            dpath = ROOT / dname
            if not dpath.exists():
                print(f'  (skip, not found: {dname}/)')
                continue
            print(f'  {dname}/ ...')
            count_before = file_count
            add_dir_to_zip(zf, dpath, TOP_DIR_NAME)
            # Count files added
            for root, _, files in os.walk(dpath):
                for f in files:
                    full = Path(root) / f
                    rel = str(full.relative_to(ROOT))
                    if not matches_exclusion(full, rel):
                        file_count += 1
                        byte_count += full.stat().st_size
            print(f'    {file_count - count_before} files')

    zip_size = OUT_ZIP.stat().st_size
    print()
    print('=== Done ===')
    print(f'  files in zip:    {file_count}')
    print(f'  uncompressed:    {byte_count / 1024:.1f} KB ({byte_count / 1024 / 1024:.2f} MB)')
    print(f'  compressed:      {zip_size / 1024:.1f} KB ({zip_size / 1024 / 1024:.2f} MB)')
    print(f'  compression:     {(1 - zip_size / byte_count) * 100:.1f}%')
    print(f'  output path:     {OUT_ZIP}')
    print()
    print('To download:')
    print(f'  {OUT_ZIP}')


if __name__ == '__main__':
    main()
